console.log("*******Step-1********");
console.log("________Number________");
var roleNumber= 68;
var age= 25;
var weight= 80;
console.log("RoleNumber:", roleNumber, "Type:", typeof roleNumber);
console.log("Age:", age, "Type:", typeof age);
console.log("Weight:", weight, "Type:", typeof weight);
console.log("________String________");
var myName="Ajay";
var graduation="BSc";
var university="MPKV";
console.log("MyName:",myName,"Type:",typeof myName);
console.log("Graduation:",graduation, "Type:",typeof graduation);
console.log("University:",university, "Type",typeof university);
console.log("________Boolean________");
var isMarried=false;
var isLazy=false;
var isFresher=true;
console.log("Married:",isMarried, "Type:",typeof isMarried);
console.log("Lazy:",isLazy, "Type:", typeof isLazy);
console.log("Fresher:", isFresher, "Type:", typeof isFresher);
console.log("=================================================================================================");
console.log("********Step-2*********");
console.log("________Difference Between null and undefined________");
console.log("null- null means the value of the variable is none or nothing . Data type of null value is Object");
console.log("--------------------------------------------------------------------------------------------------");
console.log("undefined- undefined means When we declare the variable but we dont give any value to it then it shows undefined. In that time the default value of variable is undefined. the Datat type is also undefined.");