console.log("********Step-1********");
console.log("----------Before Initialization--------");
var bankName;
console.log("Bank Name:",bankName, "Type:",typeof bankName);
console.log("----------After Initialization--------");
var bankName="SBI Bank";
console.log("Bank Name:", bankName,"Type:",typeof bankName);
console.log("********Step-2********");
var marks='90%';
console.log("Marks:",marks,"Type:",typeof marks);
console.log("********Step-3********");
console.log("----------Before Initialization--------");
var isWorking;
console.log("Is working:",isWorking, "Type:",typeof isWorking);
console.log("----------After Initialization--------");
var isWorking=true;
console.log("Is working:",isWorking, "Type:",typeof isWorking);
console.log("********Step-4********");
var totalCount= "Hundred and Seven";
//console.log("--------a.--------");
console.log("a-","Total Count:",totalCount,"Type:",typeof totalCount);
var totalCount= 107;
console.log("b-","Total Count:",totalCount,"Type:",typeof totalCount);
