console.log("================= Array Assignment A =================");
const arraySeasonalFruits= ["Banana", "Orange", "Apple", "Mango", "Water Melon"];
console.log(`Given Array: ${arraySeasonalFruits}`);
const firstElement = arraySeasonalFruits[0];
const lastElement = arraySeasonalFruits[arraySeasonalFruits.length-1];
console.log(`1.1] In the Given array First Element is: '${firstElement}'`);
console.log(`     In the Given array Last Element is: '${lastElement}'`);
console.log("-------------------------------------------------------------------");
console.log(`1.2] Before Addition of 'Papaya': ${arraySeasonalFruits}`);
const adding = arraySeasonalFruits.unshift("Papaya");
console.log(`     After Addition of 'Papaya': ${arraySeasonalFruits}`);
console.log("-------------------------------------------------------------------");
console.log(`1.3] Before Removing of 'Mango': ${arraySeasonalFruits}`);
const removing = arraySeasonalFruits.splice(4,1);
console.log(`     After Removing of 'Mango': ${arraySeasonalFruits}`);
console.log("-------------------------------------------------------------------");
console.log(`1.4] Before Addition of 'Pineapple': ${arraySeasonalFruits}`);
const additionPineapple= arraySeasonalFruits.push("Pineapple");
console.log(`     After Adding of 'Pineapple': ${arraySeasonalFruits}`);
console.log("-------------------------------------------------------------------");
console.log(`1.5] Before Inserting 'Dragon Fruit' before the 'Water Melon' : ${arraySeasonalFruits}`);
const insertDragonFruit = arraySeasonalFruits.splice(4,0,"Dragon fruit");
console.log(`     After Inserting 'Dragon Fruit' before the 'Water Melon': ${arraySeasonalFruits}`);
console.log("-------------------------------------------------------------------");
console.log(`1.6] Before Replacing 'Orange' with 'Kiwi': ${arraySeasonalFruits}`);
const replace = arraySeasonalFruits.splice(2,1,"Kiwi");
console.log(`     After Replacing 'Orange' with 'Kiwi : ${arraySeasonalFruits}`);
console.log("-------------------------------------------------------------------");
console.log(`1.7] Before Selection: ${arraySeasonalFruits}`);
const selection = arraySeasonalFruits.slice(1,5);
console.log(`     Selected element from index 1 to 4: ${selection}`);
console.log("-------------------------------------------------------------------");
console.log(`1.8] Array : ${arraySeasonalFruits}`);
const selectionlast3element= arraySeasonalFruits.slice(arraySeasonalFruits.length-3);
console.log(`     Last 3 elements: ${selectionlast3element}`);
